In [6]:
import numpy as np
import pandas as pd
import sys

In [8]:
A = [1,2,3,4,5,6]
type(A)

list

In [5]:
B = np.array([1,2,3,4,5])
type(B) #ND N-Dimensional

numpy.ndarray

In [9]:
#Size of array (in memory, bytes)
size_array = sys.getsizeof(1) * len(A)
print("Size of Array A: ", size_array)

Size of Array A:  168


In [10]:
#Size of numpy array
size_numpy = B.itemsize * B.size
print("Size of Array B", size_numpy)

Size of Array B 20


In [12]:
#Matrix of 2*5
C = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10]
])
C

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [14]:
C.shape

(2, 5)

In [16]:
C.flatten().shape

(10,)

In [17]:
C.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [18]:
C.reshape(-1,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [20]:
C.reshape(5,-1,1)

array([[[ 1],
        [ 2]],

       [[ 3],
        [ 4]],

       [[ 5],
        [ 6]],

       [[ 7],
        [ 8]],

       [[ 9],
        [10]]])

In [25]:
D = np.arange(0,100)
D.shape

(100,)

In [28]:
D.reshape(4,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [30]:
zeros = np.zeros([10,2])
zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [31]:
ones = np.ones([10,2])
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [32]:
E = np.array([1,2,3])
E*2

array([2, 4, 6])

In [33]:
F = np.array([4,5,6])
E+F

array([5, 7, 9])

In [34]:
G = np.array([1,1,1])
E+G

array([2, 3, 4])

In [35]:
E.mean()

2.0

In [38]:
H = np.array([1,2,0,4,5,6])
I = np.where(H>2)
I

(array([3, 4, 5], dtype=int64),)

@#Dot Product

In [41]:
def dot_product(a,b):
    result = 0
    for i in range(len(a)):
        result = result + a[i]*b[i]
    return result

In [39]:
J = np.random.randn(1000)
K = np.random.randn(1000)
print(J)

[-0.4892249   0.55141352  0.47403948  0.04591817 -0.53910646  0.87796933
  0.63045928 -1.3901095   0.57206938 -0.77660052 -0.15440388  1.13443999
  1.19862319  0.41779516 -0.33181265  1.87991155 -0.25882854  0.37231579
 -0.94572255 -0.2647255   0.98484865 -1.91911551  1.24685093  0.05676324
 -0.49749741  0.24230245 -1.3766243  -0.54504086 -0.23231776  0.14274657
  0.37309489 -0.21887237  1.12299622  0.20053479 -0.57567286 -0.65590565
  0.37305498  0.53423626 -0.19231649 -0.28349298  1.96847323 -1.61105439
  0.40469564 -1.29138768 -0.01979961  0.00539167  0.35063378  0.18219975
  0.93309947  1.71024909  0.49767404 -0.27372928  0.1955843   0.09458351
  0.28361451  1.13119979 -0.04180054  0.03746822  0.46185463 -0.17181287
  0.3967963  -1.0587896  -0.99528084 -2.11609957  0.51903352 -0.01587137
  0.42185728 -1.64038174  1.68075094  0.81601016  1.5669497  -1.38622059
  0.21398314  0.4668287  -0.94593947 -0.29869515  1.42203966  0.72795169
  1.10205675 -0.53645819  2.16023641 -0.86328168 -0

In [42]:
print(dot_product(J,K))

-11.499003799268426


In [45]:
import time

start = time.time()
total = time.time() - start
total

0.0